[General]
loglevel = notify
show-error-page-for-reject = true

wifi-assist = false
all-hybrid = false
ipv6 = false // 如无特殊需求不应开启 IPv6，目前网络环境下 IPv6 只会带来问题。
ipv6-vif = disabled
udp-priority = false

use-local-host-item-for-proxy = true
exclude-simple-hostnames = true
read-etc-hosts = true

test-timeout = 3
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
proxy-test-url = http://latency-test.skk.moe/endpoint

dns-server = 223.5.5.5, 119.29.29.29
encrypted-dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
encrypted-dns-follow-outbound-mode = false
hijack-dns = *:53

always-real-ip = *.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.logon.battlenet.com.cn, *.logon.battle.net, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net, stun.l.google.com, stun.*, *.turn.twilio.com, *.stun.twilio.com, stun.syncthing.net, link-ip.nextdns.io

skip-proxy = localhost, *.local, captive.apple.com, guzzoni.apple.com, passenger.t3go.cn, wxh.wo.cn, 0.0.0.0/8, 10.0.0.0/8, 17.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 192.88.99.0/24, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32

http-listen = 127.0.0.1
socks5-listen = 127.0.0.1
allow-hotspot-access = false
allow-wifi-access = false
proxy-restricted-to-lan = true

udp-policy-not-supported-behaviour = REJECT
http-api-tls = false
http-api-web-dashboard = false
geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

[Proxy Group]
#!include Node.conf
#!include Proxy.conf

[Rule]
#!include Proxy.conf

[Host]
#!include Proxy.conf

[URL Rewrite]
#!include Proxy.conf

[Header Rewrite]
#!include Proxy.conf

[MITM]
#!include Proxy.conf
